### ISSUE TITLE
Link in Module 3 yellowdig assignment is broken

### ISSUE THREAD

**Issue by DSwan23** [Watts-College/cpp-526-sum-2023#2]
The first link in the assignment description no longer works, https://cran.r-project.org/web/views/Graphics.html , page throws a 404 error

**Comment by lecy** [comment]
it looks like they stopped maintaining that task view, but you can access an archival version:

https://web.archive.org/web/20210224173945/https://cran.r-project.org/web/views/Graphics.html

**Comment by gmcirco** [comment]
Thanks. I have adjusted the link to point to the archival source.
