### ISSUE TITLE
Yellowdig topics

### ISSUE THREAD

**Issue by DSwan23** [Watts-College/cpp-526-sum-2023#3]
There only seems to be a single topic for the Yellowdig forum. It only allows for the introduction topic to be assigned to the posts, are there supposed to be more topics to choose from?

**Comment by gmcirco** [comment]
For simplicity, feel free to just create a post with a noteworthy title (e.g. "Week 3: Specialized R Graphics for [my job]"). As you post I am able to review the topics as the come up.
