### ISSUE TITLE
Percentages 

### ISSUE THREAD

**Issue by Rachel-Judd** [Watts-College/cpp-526-sum-2023#6]
What is the best way to go about adding percentages to a table? 

For example, on question 3 in Module 5, I created a new variable "harm" that shows whether a fatalty or injury occured. Then I create a table to summarize what days these occured on. How do I then generate another column showing the percentage of incidents resulting in harm on each day? 

```
dat$harm <- dat$Totalinjuries > 0 | dat$Totalfatalities > 0
table(dat$day, dat$harm=="TRUE")

      FALSE TRUE
  Mon  2872 1222
  Tue  3153 1503
  Wed  3228 1483
  Thu  3240 1574
  Fri  3525 1481
  Sat  2239  805
  Sun  1569  576
```

**Comment by lecy** [comment]
Core R something like:

```
d$tot <- d$F + d$T
d$p <- d$T / d$tot
```

But dplyr will be easier.
