### ISSUE TITLE
RenderPlot and geom_line

### ISSUE THREAD

**Issue by mbrentli** [Watts-College/cpp-526-sum-2023#9]
I'm trying to make a final tab with a line graph that shows count of accidents (y axis) by age group (x axis) depending on whether the selected input is male or female.

I've done some data manipulation in the first chunk to create a 'long' dataset, and used ggplot to plot the line, but it's not responding to the input.

I've searched online to try to find a solution, and tried 20 different things, but I can't get it to respond to the selectInput.  Quite frankly, I'm just happy that the line graph shows up at all - that was an accomplishment!  But I'd love for it do actually be reactive (and not look wonky).  I feel like it's something super simple, but I can't find the needle in a haystack!

Here's the data manipulation I've done:

`# Personal DATA PREPROCESSING V: Long Dataset
mynewdata<-dat%>%
  filter(Gender_Drv1=="Male"|Gender_Drv1=="Female")%>%
  group_by(Gender_Drv1)%>%
 summarise(
    count=n(),
    Youth=sum(age.cat=="Youth"),
    YoungAdult=sum(age.cat=="Young Adult"),
    Adult=sum(age.cat=="Adult"),
    Senior=sum(age.cat=="Senior"))

mynewdatalong<-mynewdata%>%
  select(!count)%>%
  pivot_longer(
    cols = !Gender_Drv1, 
    names_to = "AgeGroup", 
    values_to = "count") 
`

And here's the section for that tab:

`TESTLINEGRAPH {data-orientation=rows}
=====================================  

Inputs {.sidebar}
-------------------------------------
Driver Characteristics

```{r}

radioButtons(inputId = "gender", 
            label = h3("Gender of Driver at Fault"), 
            choices = c("Male", "Female"), 
            selected = "Male")


```

Outputs
-------------------------------------

### Age Distribution of accidents by gender

```{r}
renderPlot({
mynewdatalong%>%
ggplot()+
    geom_line(aes(
        x = AgeGroup, 
        y = count, 
        group=input$gender,
        col=input$gender))
})
```

`

When I select Male or Female, the legend changes, but nothing on the graph changes.

I took out the input and just plotted by group to make sure the data was set up properly to make two distinct lines and it works perfectly.  

Obviously the input markers are not placed or referenced correctly in the geom_line() but I can't figure out exactly where I'm going wrong.

Can anyone give me any hints without telling me the answer?  🙂

**Comment by mbrentli** [comment]
and, wow - sorry for that CRAZY formatting!

**Comment by mbrentli** [comment]
After looking at the other issue with the bar graphs, I also tried this:

`{r}
renderPlot({
mynewdatalong%>%
    filter(Gender_Drv1 %in% input$gender)
ggplot()+
    geom_line(aes(x = AgeGroup, y = count, group=Gender_Drv1,col=Gender_Drv1))
  
})
`

but then I get the dreaded Error:[object Object]

**Comment by mbrentli** [comment]
(and on a side note - how do you get the code chunks to consistently show up as actual chunks!?!?!)

**Comment by gmcirco** [comment]
I think you are missing a pipe in your code here. Try this:

```
renderPlot({
mynewdatalong%>%
filter(Gender_Drv1 %in% input$gender) %>%
ggplot()+
geom_line(aes(x = AgeGroup, y = count, group=Gender_Drv1,col=Gender_Drv1))

```

**Comment by mbrentli** [comment]
I knew it was something simple!  That worked (and created a host of other issues to fix - but I think I've got a better handle on those now that it's actually working).  Thank you!
